services:
  - type: web
    name: market-fraud-detection
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: MFD_SECRET_KEY
        value: change-me
      - key: DATABASE_URL
        fromDatabase:
          name: market-fraud-db
          property: connectionString
databases:
  - name: market-fraud-db
    plan: free
